apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: partition-productpage-reviews
  namespace: bookinfo
spec:
  action: partition
  mode: all
  selector:
    namespaces: [bookinfo]
    labelSelectors:
      app: productpage
  direction: both
  target:
    mode: all
    selector:
      namespaces: [bookinfo]
      labelSelectors:
        app: reviews
  duration: "5m"
